### ISSUE TITLE
Show button only when a script is matching the page

### ISSUE THREAD

**Issue by jesus2099** [gera2ld/Violentmonkey-oex#29]
We currently have the option to always show VM button or never.

As the main (sole) purpose of this button is to activate/deactivate scripts when available, it would be very nice to have a third option to **display the VM button when 1+ user script** has **matching** `@include` or `@match` (whether those scripts are activated by user or not).

 right ?

**Comment by jesus2099** [comment]
Hi @gera2ld, could you release the next version with all the [awaiting changes](/gera2ld/Violentmonkey-oex/compare/v1.6.8...master) ? :)

**Comment by gera2ld** [comment]
Released.

**Comment by jesus2099** [comment]
Excellent, thanks ! :)

**Comment by jesus2099** [comment]
Hello @gera2ld. I’m back in this ticket after much time using your great extension.
In fact now that you have added the count badge, the hiding of the button, when script count is `0`, is not so useful.
Feel free to remove this feature if you can gain some simplicity, as the original requester (me) is not even using it any more (because the badge thing you added simultaneously is so much better).
I’m sorry but maybe you’ll take this revert opportunity with pleasure. :)

**Comment by gera2ld** [comment]
OK, this feature will be removed.
