### ISSUE TITLE
Firefox rollback messed up violentmonkey

### ISSUE THREAD

**Issue by rayman89** [gera2ld/Violentmonkey-oex#51]
I did a rollback from firefox 57 beta to firefox 56 release with a fresh new install but keeping the profile folder and when I did that on firefox 56 the scripts in violentmonkey appear as loading... in the control panel and they do not function but in firefox 57 they work properly.

I saw on the faq it says that there is an option to export scripts but I was not able to find that only the import button so i was not able to test that workaround.

One drive and dropbox sincronization both fail also.

**Comment by gera2ld** [comment]
Firefox may upgrade its profile on updates, which prevents old versions of Firefox to load data correctly. If Firefox cannot provide data correctly, extensions fail.

Unfortunately Violentmonkey can do nothing with it.

**Comment by rayman89** [comment]
I found a backup I had. Is a bit older which fodlers can I put to recover my data without restoring the whole old profile.

**Comment by rayman89** [comment]
I mean 

What files from the old profile do I need to move to the new one to recover violentmonkey's config without restoring the whole old profile?
